"""
ArmoredVision V2 — Shopee browser recommendation probe (manual verification).

Opens the original Shopee short product link in a real Chrome window. If
Shopee presents its normal verification/CAPTCHA, the operator may complete it
manually. This script does not solve, bypass, or automate the verification.

After the PDP is reached, it captures recommendation responses generated by
Shopee's own frontend and reports benchmark hits.

Usage:
  python scripts/probe_shopee_recommendations_manual.py
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from playwright.sync_api import sync_playwright

SHORT_URL = "https://s.shopee.com.br/8KolJcZrfU"
TARGET_PATHS = (
    "/api/v4/recommend/product_detail_page",
    "/api/v4/recommend/recommend_post",
    "/api/v4/recommend/recommend_v2",
)
KNOWN_BENCHMARK_IDS = {
    "1609734117:22794532266",
    "329536801:28939276497",
    "335209020:29176620632",
    "382998202:23198215253",
}
OUTPUT = Path("storage/vision_v2_source_lab/shopee_recommendations_manual.json")


def extract_items(value: Any) -> list[dict[str, Any]]:
    found: dict[str, dict[str, Any]] = {}

    def walk(node: Any) -> None:
        if isinstance(node, dict):
            shop = node.get("shopid", node.get("shopId"))
            item = node.get("itemid", node.get("itemId"))
            if shop is not None and item is not None:
                key = f"{shop}:{item}"
                found[key] = {
                    "id": key,
                    "shop_id": str(shop),
                    "item_id": str(item),
                    "name": node.get("name", node.get("title")),
                    "image": node.get("image"),
                }
            for child in node.values():
                walk(child)
        elif isinstance(node, list):
            for child in node:
                walk(child)

    walk(value)
    return list(found.values())


def main() -> int:
    captured: list[dict[str, Any]] = []

    with sync_playwright() as p:
        browser = p.chromium.launch(channel="chrome", headless=False)
        context = browser.new_context(
            locale="pt-BR",
            viewport={"width": 1440, "height": 1000},
        )
        page = context.new_page()

        def on_response(response) -> None:
            if not any(path in response.url for path in TARGET_PATHS):
                return
            try:
                body = response.json()
            except Exception:
                body = {"raw_text": response.text()[:20000]}

            items = extract_items(body)
            ids = {x["id"] for x in items}
            captured.append({
                "endpoint": next(
                    (path for path in TARGET_PATHS if path in response.url),
                    None,
                ),
                "url": response.url,
                "status": response.status,
                "discovered_items": len(items),
                "known_benchmark_hits": sorted(ids & KNOWN_BENCHMARK_IDS),
                "items": items,
            })

        page.on("response", on_response)

        print(f"Opening: {SHORT_URL}")
        response = page.goto(
            SHORT_URL,
            wait_until="domcontentloaded",
            timeout=60000,
        )
        print(f"INITIAL_STATUS={response.status if response else None}")
        print(f"INITIAL_URL={page.url}")
        print(f"INITIAL_TITLE={page.title()}")
        print()
        print("Se a Shopee mostrar verificacao/CAPTCHA, conclua MANUALMENTE.")
        print("Nao tente automatizar ou contornar a verificacao.")
        print("Depois que o PRODUTO estiver aberto, pressione ENTER aqui.")
        input()

        page.wait_for_timeout(8000)

        result = {
            "status": "PROBE_ONLY",
            "mode": "manual_browser_interception",
            "short_url": SHORT_URL,
            "final_url": page.url,
            "title": page.title(),
            "captured_recommendation_responses": captured,
            "benchmark_policy": {
                "known_ids_are_post_response_labels_only": True,
                "known_ids_were_not_sent_to_shopee": True,
            },
        }

        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(
            json.dumps(result, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )

        print()
        print(json.dumps({
            "status": "PROBE_ONLY",
            "output": str(OUTPUT),
            "final_url": page.url,
            "title": page.title(),
            "captured": [
                {
                    "endpoint": x["endpoint"],
                    "status": x["status"],
                    "discovered_items": x["discovered_items"],
                    "known_benchmark_hits": x["known_benchmark_hits"],
                }
                for x in captured
            ],
        }, ensure_ascii=False, indent=2))

        browser.close()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
