"""
ArmoredVision V2 — Shopee browser-interception probe.

Plain requests to Shopee /api/v4/recommend/* are returning HTTP 403.
Current reverse-engineering evidence indicates protected /api/v4 calls require
per-request anti-bot signatures minted by Shopee's own browser JavaScript.

This probe therefore does NOT call the API itself. It opens the real BR PDP in
a visible Chrome session and captures the recommendation response generated by
Shopee's own frontend.

Requires:
  pip install playwright
  playwright install chromium

Usage:
  python scripts/probe_shopee_recommendations_browser.py
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

from playwright.sync_api import sync_playwright

SHOP_ID = 382998202
ITEM_ID = 23298215147
PRODUCT_URL = f"https://shopee.com.br/product/{SHOP_ID}/{ITEM_ID}"
KNOWN_BENCHMARK_IDS = {
    "1609734117:22794532266",
    "329536801:28939276497",
    "335209020:29176620632",
    "382998202:23198215253",
}
OUTPUT = Path("storage/vision_v2_source_lab/shopee_recommendations_browser.json")
TARGET_PATH = "/api/v4/recommend/product_detail_page"


def extract_items(value: Any) -> list[dict[str, Any]]:
    found: dict[str, dict[str, Any]] = {}

    def walk(node: Any) -> None:
        if isinstance(node, dict):
            shop = node.get("shopid", node.get("shopId"))
            item = node.get("itemid", node.get("itemId"))
            if shop is not None and item is not None:
                key = f"{shop}:{item}"
                found[key] = {
                    "id": key,
                    "shop_id": str(shop),
                    "item_id": str(item),
                    "name": node.get("name", node.get("title")),
                    "image": node.get("image"),
                }
            for child in node.values():
                walk(child)
        elif isinstance(node, list):
            for child in node:
                walk(child)

    walk(value)
    return list(found.values())


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--timeout-ms", type=int, default=45000)
    parser.add_argument("--headless", action="store_true",
                        help="Diagnostic only; headed Chrome is preferred.")
    args = parser.parse_args()

    captured: list[dict[str, Any]] = []

    with sync_playwright() as p:
        browser = p.chromium.launch(
            channel="chrome",
            headless=args.headless,
        )
        context = browser.new_context(
            locale="pt-BR",
            viewport={"width": 1440, "height": 1000},
        )
        page = context.new_page()

        def on_response(response) -> None:
            if TARGET_PATH not in response.url:
                return
            try:
                body = response.json()
            except Exception:
                body = {"raw_text": response.text()[:20000]}
            items = extract_items(body)
            ids = {x["id"] for x in items}
            captured.append({
                "url": response.url,
                "status": response.status,
                "discovered_items": len(items),
                "known_benchmark_hits": sorted(ids & KNOWN_BENCHMARK_IDS),
                "items": items,
                "response": body,
            })

        page.on("response", on_response)

        print(f"Opening: {PRODUCT_URL}")
        page.goto(PRODUCT_URL, wait_until="domcontentloaded", timeout=args.timeout_ms)
        page.wait_for_timeout(15000)

        result = {
            "status": "PROBE_ONLY",
            "mode": "browser_interception",
            "target": {"shop_id": SHOP_ID, "item_id": ITEM_ID},
            "product_url": PRODUCT_URL,
            "captured_recommendation_responses": captured,
            "benchmark_policy": {
                "known_ids_are_post_response_labels_only": True,
                "known_ids_were_not_sent_to_shopee": True,
            },
        }

        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(
            json.dumps(result, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )

        print(json.dumps({
            "status": "PROBE_ONLY",
            "output": str(OUTPUT),
            "captured": [
                {
                    "status": x["status"],
                    "discovered_items": x["discovered_items"],
                    "known_benchmark_hits": x["known_benchmark_hits"],
                }
                for x in captured
            ],
        }, ensure_ascii=False, indent=2))

        browser.close()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
